version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  az-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

volumes:
 mongodb_data_container:
