version: '3.8'
services:
 mongo:
   image: mongo
   restart: always
   environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: pass
   ports:
     - 27017:27017
   volumes:
     - mongodb_data_container:/data/db

volumes:
 mongodb_data_container:
